"""TTS machine film: one lead becoming a customer, built by students.

Headless and reproducible:

  Blender -b -P blender/machine.py -- --mode stills  --out DIR
  Blender -b -P blender/machine.py -- --mode frames  --out DIR --frames 1-60 [--portrait] [--res 320]
  Blender -b -P blender/machine.py -- --mode check

Modelled parts (writer, mailbox, city buildings, desk props) were generated by
Nalana and live in blender/parts/*.blend. Everything else, the layout, the
mechanisms, the materials, the light, the camera and every keyframe, is built
here. Ball motion is integrated from simple gravity-on-a-track math and then
checked against every collider, per frame, before anything renders. A ball that
touches geometry stops the script.
"""

import argparse
import math
import os
import random
import re
import sys

import bmesh
import bpy
import numpy as np
from bpy_extras import anim_utils
from mathutils import Matrix, Quaternion, Vector
from mathutils.bvhtree import BVHTree

HERE = os.path.dirname(os.path.abspath(__file__))
PARTS = os.path.join(HERE, "parts")

FPS = 30
FRAMES = 375  # 12.5 s
T0 = -1.5  # scene time at frame 1: the opening rack happens while the hero waits in the queue
R = 0.1  # ball radius, scene units
G = 7.0  # toy gravity, units/s^2; 9.8 made the balls read as tiny and frantic
P = 40 / FPS  # one ball released every 40 frames
HERO = 0
ACCEPT_EVERY = 3  # the sorter passes one ball in three, the hero among them

HEX = {
    "ground": "F4EFE6",
    "cardinal": "990000",
    "gold": "FFCC00",
    "cream": "FBF5E6",
    "sky": "5FA8E0",
    "ink": "1A1416",
    "lilac": "B7A6D6",
    "creamdeep": "EFE4CB",
}


def srgb_to_lin(c):
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def hexcol(h):
    h = HEX.get(h, h)
    return tuple(srgb_to_lin(int(h[i:i + 2], 16) / 255) for i in (0, 2, 4)) + (1.0,)


# ---------------------------------------------------------------- utilities

def smooth(x):
    x = min(max(x, 0.0), 1.0)
    return x * x * (3 - 2 * x)


def smoother(x):
    x = min(max(x, 0.0), 1.0)
    return x * x * x * (x * (6 * x - 15) + 10)


def ramp(t, t0, t1):
    return smoother((t - t0) / (t1 - t0)) if t1 > t0 else float(t >= t1)


def back_out(x, s=1.6):
    x = min(max(x, 0.0), 1.0)
    x -= 1
    return x * x * ((s + 1) * x + s) + 1


def link(obj, coll=None):
    (coll or bpy.context.scene.collection).objects.link(obj)
    return obj


def new_mesh_obj(name, bm, mat=None, smooth_shade=True):
    me = bpy.data.meshes.new(name)
    bm.to_mesh(me)
    bm.free()
    if smooth_shade:
        me.shade_smooth()
    ob = bpy.data.objects.new(name, me)
    if mat:
        me.materials.append(mat)
    return link(ob)


def rounded_box(name, size, mat, bevel=0.03, location=(0, 0, 0), subdiv=1, wobble=0.0):
    bm = bmesh.new()
    bmesh.ops.create_cube(bm, size=1.0)
    for v in bm.verts:
        v.co = Vector((v.co.x * size[0], v.co.y * size[1], v.co.z * size[2]))
    ob = new_mesh_obj(name, bm, mat)
    ob.location = location
    m = ob.modifiers.new("bevel", "BEVEL")
    m.width = min(bevel, min(size) * 0.49)
    m.segments = 4
    m.limit_method = "NONE"
    if subdiv:
        s = ob.modifiers.new("subd", "SUBSURF")
        s.levels = s.render_levels = subdiv
    if wobble:
        add_wobble(ob, wobble)
    return ob


def cylinder(name, radius, depth, mat, location=(0, 0, 0), segments=48, bevel=0.015, axis="Z"):
    bm = bmesh.new()
    bmesh.ops.create_cone(bm, cap_ends=True, cap_tris=False, segments=segments,
                          radius1=radius, radius2=radius, depth=depth)
    if axis == "X":
        bmesh.ops.rotate(bm, verts=bm.verts, cent=(0, 0, 0), matrix=Matrix.Rotation(math.pi / 2, 3, "Y"))
    elif axis == "Y":
        bmesh.ops.rotate(bm, verts=bm.verts, cent=(0, 0, 0), matrix=Matrix.Rotation(math.pi / 2, 3, "X"))
    ob = new_mesh_obj(name, bm, mat)
    ob.location = location
    if bevel:
        m = ob.modifiers.new("bevel", "BEVEL")
        m.width = min(bevel, radius * 0.45, depth * 0.45)
        m.segments = 4
        m.limit_method = "ANGLE"
    return ob


def sphere(name, radius, mat, location=(0, 0, 0)):
    bm = bmesh.new()
    bmesh.ops.create_uvsphere(bm, u_segments=48, v_segments=24, radius=radius)
    ob = new_mesh_obj(name, bm, mat)
    ob.location = location
    return ob


_wobble_tex = None


def add_wobble(ob, strength):
    """Low-frequency displacement: hand-made, not machined."""
    global _wobble_tex
    if _wobble_tex is None:
        _wobble_tex = bpy.data.textures.new("wobble", "CLOUDS")
        _wobble_tex.noise_scale = 0.35
    d = ob.modifiers.new("wobble", "DISPLACE")
    d.texture = _wobble_tex
    d.strength = strength
    d.mid_level = 0.5
    d.texture_coords = "GLOBAL"


# ---------------------------------------------------------------- materials

_mats = {}

# Which look the materials and light are built in. "v1" is the look the /way
# film shipped in (2026-10-05, matched to Clay's Orch loop). Caleb, 2026-10-10,
# set the about render beside clay.com: "Ours is so lame the clay one is
# YAYYYYYY". Measured on that render (machine-1280.webp): mean saturation
# 0.089 over the frame, 1.7% of pixels above 0.3, so it read as pale plastic
# under a flat sky. "v2" is real
# clay: saturated colour, a visible grain, light that scatters under the skin,
# warm occlusion where things meet, and contact shadows from one soft key.
# Set with --look; heroes.py always builds in v2.
LOOK = {"name": "v1"}


def clay(key, color=None, rough=0.58, bump=1.0):
    """Matte clay: soft sheen, fine grain bump, a slow lumpy bump, tiny value drift."""
    name = f"clay_{key}_{LOOK['name']}"
    if name in _mats:
        return _mats[name]
    col = hexcol(key) if color is None else color
    m = bpy.data.materials.new(name)
    m.use_nodes = True
    nt = m.node_tree
    nt.nodes.clear()
    out = nt.nodes.new("ShaderNodeOutputMaterial")
    bsdf = nt.nodes.new("ShaderNodeBsdfPrincipled")
    bsdf.inputs["Roughness"].default_value = rough
    bsdf.inputs["Specular IOR Level"].default_value = 0.32
    bsdf.inputs["Sheen Weight"].default_value = 0.12
    bsdf.inputs["Sheen Roughness"].default_value = 0.6
    bsdf.inputs["Subsurface Weight"].default_value = 0.04
    bsdf.inputs["Subsurface Radius"].default_value = (1.0, 0.55, 0.35)
    bsdf.inputs["Subsurface Scale"].default_value = 0.004
    tc = nt.nodes.new("ShaderNodeTexCoord")
    fine = nt.nodes.new("ShaderNodeTexNoise")
    fine.inputs["Scale"].default_value = 140.0
    fine.inputs["Detail"].default_value = 3.0
    lump = nt.nodes.new("ShaderNodeTexNoise")
    lump.inputs["Scale"].default_value = 7.0
    lump.inputs["Detail"].default_value = 2.0
    nt.links.new(tc.outputs["Object"], fine.inputs["Vector"])
    nt.links.new(tc.outputs["Object"], lump.inputs["Vector"])
    b1 = nt.nodes.new("ShaderNodeBump")
    b1.inputs["Strength"].default_value = 0.10 * bump
    b1.inputs["Distance"].default_value = 0.002
    b2 = nt.nodes.new("ShaderNodeBump")
    b2.inputs["Strength"].default_value = 0.06 * bump
    b2.inputs["Distance"].default_value = 0.02
    nt.links.new(fine.outputs["Fac"], b1.inputs["Height"])
    nt.links.new(lump.outputs["Fac"], b2.inputs["Height"])
    nt.links.new(b1.outputs["Normal"], b2.inputs["Normal"])
    nt.links.new(b2.outputs["Normal"], bsdf.inputs["Normal"])
    # value drift of about 3%, so large faces do not read as flat CG fills
    mix = nt.nodes.new("ShaderNodeMix")
    mix.data_type = "RGBA"
    mix.blend_type = "MULTIPLY"
    mix.inputs["Factor"].default_value = 1.0
    mix.inputs[6].default_value = col
    ramp_n = nt.nodes.new("ShaderNodeMapRange")
    ramp_n.inputs["To Min"].default_value = 0.955
    ramp_n.inputs["To Max"].default_value = 1.025
    nt.links.new(lump.outputs["Fac"], ramp_n.inputs["Value"])
    comb = nt.nodes.new("ShaderNodeCombineColor")
    for s in ("Red", "Green", "Blue"):
        nt.links.new(ramp_n.outputs["Result"], comb.inputs[s])
    nt.links.new(comb.outputs["Color"], mix.inputs[7])
    # tight contact occlusion where things meet: what makes objects sit
    ao = nt.nodes.new("ShaderNodeAmbientOcclusion")
    ao.inputs["Distance"].default_value = 0.07
    ao.samples = 8
    aor = nt.nodes.new("ShaderNodeMapRange")
    aor.inputs["To Min"].default_value = 0.58
    aor.inputs["To Max"].default_value = 1.0
    nt.links.new(ao.outputs["AO"], aor.inputs["Value"])
    aom = nt.nodes.new("ShaderNodeMix")
    aom.data_type = "RGBA"
    aom.blend_type = "MULTIPLY"
    aom.inputs["Factor"].default_value = 1.0
    nt.links.new(mix.outputs[2], aom.inputs[6])
    acomb = nt.nodes.new("ShaderNodeCombineColor")
    for s_ in ("Red", "Green", "Blue"):
        nt.links.new(aor.outputs["Result"], acomb.inputs[s_])
    nt.links.new(acomb.outputs["Color"], aom.inputs[7])
    nt.links.new(aom.outputs[2], bsdf.inputs["Base Color"])
    nt.links.new(bsdf.outputs["BSDF"], out.inputs["Surface"])
    if LOOK["name"] == "v2":
        clay_v2(nt, bsdf, tc, fine, b1, b2, mix, aor, aom, acomb, bump)
    _mats[name] = m
    return m


def clay_v2(nt, bsdf, tc, fine, b1, b2, mix, aor, aom, acomb, bump):
    """The v2 skin on top of the v1 graph, so v1 renders stay byte-identical.

    Set by eye on the before/after crop of frame 200 (docs/INTENT-home.md,
    "the clay look"), never fitted to Clay's pixels: synthesising their look,
    not cloning it, is the brief. Treat each as guessed, then judged."""
    # Subsurface: 0.04 read as painted plastic. 0.22 at a 2cm radius lets the
    # key glow through thin edges, which is most of what makes clay read as
    # clay at this scale (the parts are 0.1 to 0.5 units, one unit a metre).
    bsdf.inputs["Subsurface Weight"].default_value = 0.22
    bsdf.inputs["Subsurface Radius"].default_value = (1.0, 0.45, 0.28)
    bsdf.inputs["Subsurface Scale"].default_value = 0.02
    bsdf.inputs["Roughness"].default_value = min(bsdf.inputs["Roughness"].default_value, 0.52)
    bsdf.inputs["Specular IOR Level"].default_value = 0.4
    # a velvet rim, the soft bright edge a matte clay surface shows at grazing angles
    bsdf.inputs["Sheen Weight"].default_value = 0.3
    bsdf.inputs["Sheen Roughness"].default_value = 0.45
    # Grain you can see: the fine noise twice as fine and nearly twice as
    # strong, plus thumb-pressed dimples from a Voronoi layer.
    fine.inputs["Scale"].default_value = 260.0
    fine.inputs["Detail"].default_value = 6.0
    b1.inputs["Strength"].default_value = 0.18 * bump
    vor = nt.nodes.new("ShaderNodeTexVoronoi")
    vor.feature = "SMOOTH_F1"
    vor.inputs["Scale"].default_value = 38.0
    nt.links.new(tc.outputs["Object"], vor.inputs["Vector"])
    b3 = nt.nodes.new("ShaderNodeBump")
    b3.inputs["Strength"].default_value = 0.07 * bump
    b3.inputs["Distance"].default_value = 0.004
    nt.links.new(vor.outputs["Distance"], b3.inputs["Height"])
    nt.links.new(b2.outputs["Normal"], b3.inputs["Normal"])
    nt.links.new(b3.outputs["Normal"], bsdf.inputs["Normal"])
    # Saturation up 25% before occlusion (v1 frame mean 0.089).
    hsv = nt.nodes.new("ShaderNodeHueSaturation")
    hsv.inputs["Saturation"].default_value = 1.25
    nt.links.new(mix.outputs[2], hsv.inputs["Color"])
    nt.links.new(hsv.outputs["Color"], aom.inputs[6])
    # Warm occlusion: creases go to a terracotta brown, never grey. The v1
    # grey multiply is what made every contact read as dust.
    warm = nt.nodes.new("ShaderNodeValToRGB")
    warm.color_ramp.elements[0].position = 0.0
    warm.color_ramp.elements[0].color = (0.30, 0.13, 0.08, 1.0)
    warm.color_ramp.elements[1].position = 1.0
    warm.color_ramp.elements[1].color = (1.0, 1.0, 1.0, 1.0)
    aor.inputs["To Min"].default_value = 0.35
    nt.links.new(aor.outputs["Result"], warm.inputs["Fac"])
    nt.links.new(warm.outputs["Color"], aom.inputs[7])


def reskin(ob):
    """Nalana parts arrive with their own Principled setups. Re-skin them with
    the house clay so every object shares one material language, and push any
    green to lilac (the one secondary) and any orange to gold."""
    if ob.type not in {"MESH", "CURVE"}:
        return
    data = ob.data
    for i, slot in enumerate(data.materials):
        col = (0.8, 0.8, 0.8, 1.0)
        if slot and slot.use_nodes:
            for n in slot.node_tree.nodes:
                if n.type == "BSDF_PRINCIPLED":
                    col = tuple(n.inputs["Base Color"].default_value)
                    break
        elif slot:
            col = tuple(slot.diffuse_color)
        r, g, b = col[:3]
        if g > r * 1.05 and g > b * 1.05:
            key, c = "lilac", None
        elif r > g * 1.25 and g > b * 1.6 and r > 0.3:
            key, c = "gold", None
        else:
            key = "n_%02x%02x%02x" % tuple(int(255 * max(0, min(1, v)) ** (1 / 2.2)) for v in (r, g, b))
            c = col
        data.materials[i] = clay(key, c)
    if ob.type == "CURVE" and not data.materials:
        data.materials.append(clay("ink"))


# ---------------------------------------------------------------- light rig

# Matched to Clay's Orch loop with blender/lookdev.py on 2026-10-05: lit ground
# 0.871 vs 0.877, cast-shadow core 0.44 vs 0.46 of lit, penumbra 103 vs 96 px
# per 1000. AgX was tried first and turned USC gold into mustard and the
# backdrop grey; Standard keeps the brand colours and nothing here clips.
LIGHT = dict(key_energy=4.2, key_angle=16.0, key_elev=38.0, key_az=-35.0,
             world_strength=0.18, camera_bg=5.5, exposure=0.0, look="None", view="Standard",
             horizon="FBF8F2", zenith="EFE7DA")


# v2: the key carries the picture and the sky only fills. The world at 0.18
# against a 4.2 sun with a 16 degree disc gave cast-shadow cores 0.44 of lit
# with a penumbra 103px wide per 1000, which reads as overcast. A 6 degree
# disc and a world at 0.09 give the short dark contact shadow under every
# object; camera_bg doubles so the backdrop the camera sees stays as bright.
# The first v2 key (5.2, camera_bg 11) clipped the pulled-back frame 360 to
# floor 255,250,235 against the page ground #F4EFE6 (244,239,230) that the
# film fades into; v1 lands at 241,234,223. Key 4.4 and camera_bg 9.5 gave
# 241,233,219 floor and a backdrop of 235 against v1's 240, hence 10.
LIGHT_V2 = dict(LIGHT, key_energy=4.4, key_angle=6.0, key_elev=42.0, world_strength=0.09,
                camera_bg=10.0, horizon="FFF6EA", zenith="F2E2CC")


def light_rig(**over):
    """One big soft key, high and in front and to one side, plus a warm
    gradient environment that lifts every shadow to a warm grey-brown.
    Matched against Clay's Orch loop in blender/lookdev.py."""
    cfg = dict(LIGHT_V2 if LOOK["name"] == "v2" else LIGHT, **over)
    sc = bpy.context.scene
    sun = bpy.data.objects.new("Key", bpy.data.lights.new("Key", "SUN"))
    sun.data.energy = cfg["key_energy"]
    sun.data.angle = math.radians(cfg["key_angle"])
    sun.data.color = (1.0, 0.99, 0.975)
    sun.rotation_euler = (math.radians(90 - cfg["key_elev"]), 0, math.radians(cfg["key_az"]))
    link(sun)
    w = bpy.data.worlds.new("World")
    sc.world = w
    w.use_nodes = True
    nt = w.node_tree
    bg = next(n for n in nt.nodes if n.type == "BACKGROUND")
    bg.inputs["Strength"].default_value = cfg["world_strength"]
    # vertical gradient: bright warm white at the horizon, a touch deeper overhead
    geo = nt.nodes.new("ShaderNodeNewGeometry")
    sep = nt.nodes.new("ShaderNodeSeparateXYZ")
    nt.links.new(geo.outputs["Incoming"], sep.inputs["Vector"])
    cr = nt.nodes.new("ShaderNodeValToRGB")
    cr.color_ramp.elements[0].position = 0.0
    cr.color_ramp.elements[0].color = hexcol(cfg["horizon"])
    cr.color_ramp.elements[1].position = 0.45
    cr.color_ramp.elements[1].color = hexcol(cfg["zenith"])
    absz = nt.nodes.new("ShaderNodeMath")
    absz.operation = "ABSOLUTE"
    nt.links.new(sep.outputs["Z"], absz.inputs[0])
    nt.links.new(absz.outputs[0], cr.inputs["Fac"])
    nt.links.new(cr.outputs["Color"], bg.inputs["Color"])
    # the camera sees a brighter backdrop than the one that lights the set,
    # the way a studio sweep reads lighter than the fill it bounces
    lp = nt.nodes.new("ShaderNodeLightPath")
    bright = nt.nodes.new("ShaderNodeBackground")
    bright.inputs["Strength"].default_value = cfg["world_strength"] * cfg["camera_bg"]
    nt.links.new(cr.outputs["Color"], bright.inputs["Color"])
    mixs = nt.nodes.new("ShaderNodeMixShader")
    nt.links.new(lp.outputs["Is Camera Ray"], mixs.inputs[0])
    nt.links.new(bg.outputs[0], mixs.inputs[1])
    nt.links.new(bright.outputs[0], mixs.inputs[2])
    wout = next(n for n in nt.nodes if n.type == "OUTPUT_WORLD")
    nt.links.new(mixs.outputs[0], wout.inputs["Surface"])
    _VIEW.update(exposure=cfg["exposure"], look=cfg["look"], view=cfg["view"])
    return sun


_VIEW = dict(exposure=0.0, look="None", view="Standard")


# ---------------------------------------------------------------- parts from Nalana

def append_part(fname):
    path = os.path.join(PARTS, fname)
    with bpy.data.libraries.load(path, link=False) as (src, dst):
        dst.objects = src.objects
    coll = bpy.data.collections.new(fname.replace(".blend", ""))
    bpy.context.scene.collection.children.link(coll)
    objs = [o for o in dst.objects if o is not None]
    for o in objs:
        coll.objects.link(o)
        reskin(o)
        for m in o.modifiers:
            if m.type == "BEVEL" and getattr(m, "harden_normals", False):
                m.harden_normals = False
    return objs


def by_name(objs, name):
    """Appended names gain .001 suffixes when another part used the name first."""
    for o in objs:
        if o.name == name or re.fullmatch(re.escape(name) + r"\.\d{3}", o.name):
            return o
    raise SystemExit(f"part object {name!r} not found")


def root_of(objs, name_contains):
    for o in objs:
        if name_contains in o.name and o.parent is None:
            return o
    for o in objs:
        if name_contains in o.name:
            return o
    raise SystemExit(f"part root {name_contains!r} not found")


def place(root, location, scale, rot_z=0.0):
    holder = bpy.data.objects.new(root.name + "_place", None)
    link(holder, root.users_collection[0])
    holder.location = location
    holder.rotation_euler = (0, 0, rot_z)
    holder.scale = (scale,) * 3
    root.parent = holder
    return holder


def descendants(ob):
    out = []
    for c in ob.children:
        out.append(c)
        out += descendants(c)
    return out


def world_bbox(objs):
    pts = []
    for o in objs:
        if o.type == "MESH":
            pts += [o.matrix_world @ Vector(c) for c in o.bound_box]
    mn = Vector([min(p[i] for p in pts) for i in range(3)])
    mx = Vector([max(p[i] for p in pts) for i in range(3)])
    return mn, mx


# ---------------------------------------------------------------- tracks

def catmull(points, per_unit=60):
    pts = [Vector(p) for p in points]
    out = []
    ext = [pts[0] * 2 - pts[1]] + pts + [pts[-1] * 2 - pts[-2]]
    for i in range(1, len(ext) - 2):
        p0, p1, p2, p3 = ext[i - 1], ext[i], ext[i + 1], ext[i + 2]
        n = max(4, int((p2 - p1).length * per_unit))
        for k in range(n):
            t = k / n
            t2, t3 = t * t, t * t * t
            out.append(0.5 * ((2 * p1) + (-p0 + p2) * t + (2 * p0 - 5 * p1 + 4 * p2 - p3) * t2
                              + (-p0 + 3 * p1 - 3 * p2 + p3) * t3))
    out.append(pts[-1])
    return out


def helix(center, radius, z0, z1, a0, turns, n=240):
    out = []
    for k in range(n + 1):
        u = k / n
        a = a0 - 2 * math.pi * turns * u  # clockwise seen from above
        out.append(Vector((center[0] + radius * math.cos(a), center[1] + radius * math.sin(a), z0 + (z1 - z0) * u)))
    return out


def smooth_polyline(pts, window):
    """Moving-average the interior so joins between straight runs and the helix
    lose their crease; both ends stay exactly where they were."""
    out = [p.copy() for p in pts]
    h = window // 2
    for i in range(h, len(pts) - h):
        acc = Vector((0, 0, 0))
        for k in range(i - h, i + h + 1):
            acc += pts[k]
        out[i] = acc / window
    return out


def frames_along(axis):
    tangents, ups = [], []
    for i in range(len(axis)):
        a = axis[max(i - 1, 0)]
        b = axis[min(i + 1, len(axis) - 1)]
        t = (b - a).normalized()
        up = Vector((0, 0, 1)) - t * t.z
        tangents.append(t)
        ups.append(up.normalized())
    return tangents, ups


def strut_under(name, axis, frac, mat, floor=0.0, rc=0.14, wall=0.035):
    p = axis[int(frac * (len(axis) - 1))]
    top = p.z - rc - wall - 0.04
    return cylinder(name, 0.02, top - floor, mat, location=(p.x, p.y, floor + (top - floor) / 2))


def make_chute(name, axis, rc=0.14, wall=0.035, lip_deg=28, mat=None):
    """A half-pipe swept along the axis polyline; the lips rise past horizontal."""
    tangents, ups = frames_along(axis)
    prof = []
    a0, a1 = math.radians(-180 - lip_deg), math.radians(lip_deg)
    n = 28
    for k in range(n + 1):
        a = a0 + (a1 - a0) * k / n
        prof.append((rc * math.cos(a), rc * math.sin(a)))
    for k in range(1, 8):  # rounded lip
        a = a1 + math.pi * k / 8
        c = ((rc + wall / 2) * math.cos(a1), (rc + wall / 2) * math.sin(a1))
        prof.append((c[0] + wall / 2 * math.cos(a), c[1] + wall / 2 * math.sin(a)))
    for k in range(n, -1, -1):
        a = a0 + (a1 - a0) * k / n
        prof.append(((rc + wall) * math.cos(a), (rc + wall) * math.sin(a)))
    for k in range(1, 8):
        a = a0 + math.pi + math.pi * k / 8
        c = ((rc + wall / 2) * math.cos(a0), (rc + wall / 2) * math.sin(a0))
        prof.append((c[0] + wall / 2 * math.cos(a), c[1] + wall / 2 * math.sin(a)))
    bm = bmesh.new()
    rings = []
    for p, t, up in zip(axis, tangents, ups):
        side = t.cross(up).normalized()
        rings.append([bm.verts.new(p + side * x + up * y) for x, y in prof])
    m = len(prof)
    for i in range(len(rings) - 1):
        for k in range(m):
            bm.faces.new((rings[i][k], rings[i][(k + 1) % m], rings[i + 1][(k + 1) % m], rings[i + 1][k]))
    bm.normal_update()
    ob = new_mesh_obj(name, bm, mat or clay("cream"))
    return ob


class Track:
    """Ball-centre path for a ball riding the bottom of a half-pipe or a floor."""

    def __init__(self, centers):
        self.p = [Vector(c) for c in centers]
        self.s = [0.0]
        for a, b in zip(self.p, self.p[1:]):
            self.s.append(self.s[-1] + (b - a).length)
        self.length = self.s[-1]

    def at(self, s):
        s = min(max(s, 0.0), self.length)
        lo, hi = 0, len(self.s) - 1
        while hi - lo > 1:
            mid = (lo + hi) // 2
            if self.s[mid] <= s:
                lo = mid
            else:
                hi = mid
        seg = self.s[hi] - self.s[lo]
        u = 0.0 if seg == 0 else (s - self.s[lo]) / seg
        return self.p[lo].lerp(self.p[hi], u)

    def slope(self, s):
        a, b = self.at(s - 0.01), self.at(s + 0.01)
        d = (b - a).length
        return 0.0 if d == 0 else (b.z - a.z) / d

    def roll(self, v0, damping=0.25, vmin=1.25, vmax=4.5):
        """Integrate gravity along the track. Returns (duration, v_end, samples[(t, s)])."""
        dt = 1 / 1200
        t, s, v = 0.0, 0.0, max(v0, vmin)
        samples = [(0.0, 0.0)]
        while s < self.length:
            a = -G * self.slope(s) - damping * v
            v = min(max(v + a * dt, vmin), vmax)
            s += v * dt
            t += dt
            samples.append((t, min(s, self.length)))
        return t, v, samples


def chute_track(axis, rc=0.14):
    tangents, ups = frames_along(axis)
    # the ball rides 8 mm proud of the trough: the swept rings pinch slightly on
    # tight bends, and the audit caught 9 mm overlaps on chute 3 without this
    return Track([p - u * (rc - R - 0.008) for p, u in zip(axis, ups)])


def sample_lookup(samples, t):
    lo, hi = 0, len(samples) - 1
    if t <= 0:
        return samples[0][1]
    if t >= samples[-1][0]:
        return samples[-1][1]
    while hi - lo > 1:
        mid = (lo + hi) // 2
        if samples[mid][0] <= t:
            lo = mid
        else:
            hi = mid
    (t0, s0), (t1, s1) = samples[lo], samples[hi]
    return s0 + (s1 - s0) * (t - t0) / (t1 - t0)


# ---------------------------------------------------------------- animation writer

def fcurve_bake(id_data, path, per_index_values, start=1):
    """Write one keyframe per frame, linear, through the slotted-action API."""
    ad = id_data.animation_data_create()
    if ad.action is None:
        act = bpy.data.actions.new(f"{id_data.name}_act")
        ad.action = act
        if ad.action_slot is None:
            slot = act.slots.new(id_type=id_data.id_type, name=id_data.name)
            ad.action_slot = slot
    cb = anim_utils.action_ensure_channelbag_for_slot(ad.action, ad.action_slot)
    for idx, values in enumerate(per_index_values):
        fc = cb.fcurves.find(path, index=idx) or cb.fcurves.new(path, index=idx)
        n = len(values)
        fc.keyframe_points.clear()
        fc.keyframe_points.add(n)
        co = []
        for k, v in enumerate(values):
            co += [start + k, v]
        fc.keyframe_points.foreach_set("co", co)
        fc.keyframe_points.foreach_set("interpolation", [1] * n)  # LINEAR
        fc.update()


def bake_matrices(ob, mats):
    """mats: world (or parent-space) matrices per frame."""
    locs, rots, scs = [[], [], []], [[], [], [], []], [[], [], []]
    ob.rotation_mode = "QUATERNION"
    prev = None
    for m in mats:
        l, q, s = m.decompose()
        if prev is not None and prev.dot(q) < 0:
            q = -q
        prev = q
        for i in range(3):
            locs[i].append(l[i])
            scs[i].append(s[i])
        for i in range(4):
            rots[i].append(q[i])
    fcurve_bake(ob, "location", locs)
    fcurve_bake(ob, "rotation_quaternion", rots)
    fcurve_bake(ob, "scale", scs)


def frame_times():
    return [T0 + (f - 1) / FPS for f in range(1, FRAMES + 1)]


# ---------------------------------------------------------------- the scene

class Machine:
    def __init__(self):
        self.colliders = []  # (object, animated?)
        self.balls = []
        self.build()

    # ---- static set
    def build(self):
        sc = bpy.context.scene
        self.zd = 0.95  # desk top
        # city hopper
        self.city_c = Vector((-4.5, 0.35, 0.0))
        self.zc = 2.62  # tray top
        self.street_y = -0.275
        # qualifier pivot (also the axis height of the sorter tray)
        self.Q = Vector((-1.95, 0.075, 2.2))
        self.tray_half = 0.4
        self.tray_rc = 0.14
        self.yaw_acc = math.radians(50)
        self.yaw_rej = math.radians(-58)
        self.tilt_max = math.radians(30)
        # cart
        self.xL, self.xW, self.xD = -0.95, -0.12, 0.72
        self.bed_top = self.zd + 0.21
        self.mail_x = 1.85
        self.stack_c = Vector((3.05, -0.62, 0.0))
        self.hole_c = Vector((-1.55, -1.55, 0.0))

        self.build_ground()
        self.build_city()
        self.build_chute1()
        self.build_qualifier()
        self.build_desk_and_cart()
        self.build_writer()
        self.build_mailbox()
        self.build_reject()
        self.build_chute2()
        self.build_chute3_and_stack()
        self.build_props()
        self.build_light_world()

    def collide(self, ob, animated=False):
        self.colliders.append((ob, animated))
        return ob

    def build_ground(self):
        bm = bmesh.new()
        bmesh.ops.create_circle(bm, cap_ends=True, radius=80, segments=96)
        ground = new_mesh_obj("Ground", bm, clay("ground", rough=0.85, bump=0.6), smooth_shade=False)
        # reject hole: a real hole with a dark throat, so a falling ball reads as gone
        cutter = cylinder("HoleCutter", 0.2, 1.0, None, location=(self.hole_c.x, self.hole_c.y, 0), bevel=0)
        cutter.hide_render = cutter.hide_viewport = True
        b = ground.modifiers.new("hole", "BOOLEAN")
        b.operation = "DIFFERENCE"
        b.object = cutter
        b.solver = "EXACT"
        throat = cylinder("HoleThroat", 0.21, 0.6, clay("ink", rough=0.9), location=(self.hole_c.x, self.hole_c.y, -0.31), bevel=0)
        sol = throat.modifiers.new("shell", "SOLIDIFY")
        sol.thickness = 0.02
        # remove top cap so the throat is open
        self.collide(ground)

    def build_city(self):
        c, z = self.city_c, self.zc
        tray = rounded_box("CityTray", (1.6, 1.6, 0.14), clay("sky"), bevel=0.05,
                           location=(c.x, c.y, z - 0.07), wobble=0.004)
        self.collide(tray)
        rim_h = 0.08
        for nm, size, off in [
            ("RimBack", (1.6, 0.06, rim_h), (0, 0.77)),
            ("RimFront", (1.6, 0.06, rim_h), (0, -0.77)),
            ("RimLeft", (0.06, 1.6, rim_h), (-0.77, 0)),
            # right rim with a gap for the street exit
            ("RimRightA", (0.06, 0.9, rim_h), (0.77, 0.35)),
            ("RimRightB", (0.06, 0.29, rim_h), (0.77, -0.655)),
        ]:
            self.collide(rounded_box("City" + nm, size, clay("sky"), bevel=0.025,
                                     location=(c.x + off[0], c.y + off[1], z + rim_h / 2 - 0.01)))
        for sx in (-0.6, 0.6):
            for sy in (-0.6, 0.6):
                self.collide(cylinder("CityLeg", 0.05, z - 0.14, clay("cream"),
                                      location=(c.x + sx, c.y + sy, (z - 0.14) / 2)))
                cylinder("CityFoot", 0.09, 0.04, clay("cream"), location=(c.x + sx, c.y + sy, 0.02))
        # buildings from Nalana, one per block, plaza in the middle
        objs = append_part("city.blend")
        bnodes = sorted([o for o in objs if o.name.startswith("Building_")
                         and not (o.parent and o.parent.name.startswith("Building_"))], key=lambda o: o.name)
        blocks = [(-0.55, 0.55), (0, 0.55), (0.55, 0.55), (-0.55, 0), (0.55, 0),
                  (-0.55, -0.55), (0, -0.55), (0.55, -0.55)]
        bpy.context.view_layer.update()
        # tallest at the back, shortest along the front street so the queue of
        # leads stays in view from a front three-quarter camera
        def height(b):
            mn, mx = world_bbox([b] + descendants(b))
            return mx.z - mn.z
        bnodes = sorted(bnodes, key=height, reverse=True)
        k = 4.4
        for b, (bx, by) in zip(bnodes, blocks):
            mn, mx = world_bbox([b] + descendants(b))
            ctr = Vector(((mn.x + mx.x) / 2, (mn.y + mx.y) / 2, mn.z))
            holder = bpy.data.objects.new(b.name + "_place", None)
            link(holder, b.users_collection[0])
            holder.location = (c.x + bx, c.y + by, z)
            holder.rotation_euler = (0, 0, random.Random(b.name).uniform(-0.06, 0.06))
            holder.scale = (k,) * 3
            mw = b.matrix_world.copy()
            b.parent = holder
            b.matrix_parent_inverse = Matrix.Translation(-ctr)
            b.matrix_basis = mw
            for o in [b] + descendants(b):
                if o.type == "MESH":
                    self.collide(o)
        for o in objs:
            if o.parent is None and not o.name.startswith("Building_") and o.type == "EMPTY":
                pass
        rounded_box("CityPlaza", (0.27, 0.27, 0.04), clay("lilac"), bevel=0.015,
                    location=(c.x, c.y, z + 0.02))
        # manhole where recycled leads come back up
        self.slot_x = [0.62 - 0.3 * k_ for k_ in range(5)]
        mh = cylinder("Manhole", 0.085, 0.006, clay("ink", rough=0.8),
                      location=(c.x + self.slot_x[4], c.y + self.street_y, z + 0.0005), bevel=0.002)
        # escapement gate on a little gantry at the exit
        gx = c.x + 0.735
        for gy in (self.street_y - 0.16, self.street_y + 0.16):
            self.collide(cylinder("GatePost", 0.018, 0.3, clay("ink"), location=(gx, c.y + gy, z + 0.15)))
        self.collide(cylinder("GateBar", 0.02, 0.36, clay("ink"), location=(gx, c.y + self.street_y, z + 0.29), axis="Y"))
        self.gate_pivot = Vector((gx, c.y + self.street_y, z + 0.27))
        gate = rounded_box("Gate", (0.03, 0.24, 0.22), clay("gold"), bevel=0.012, location=(0, 0, -0.11), subdiv=0)
        gate_holder = bpy.data.objects.new("GateHinge", None)
        link(gate_holder)
        gate.parent = gate_holder
        gate_holder.location = self.gate_pivot
        self.gate = gate_holder
        self.collide(gate, animated=True)

    def build_chute1(self):
        c, z = self.city_c, self.zc
        y = c.y + self.street_y
        self.helix_c = (-2.95, y - 0.42)
        zc_axis = z + R + (self.tray_rc - R - 0.008)
        start = Vector((c.x + 0.8 + 0.02, y, zc_axis))
        top = Vector((self.helix_c[0], y, zc_axis - 0.05))
        straight1 = [start.lerp(top, k / 30) for k in range(30)]
        hel = helix(self.helix_c, 0.42, top.z, top.z - 0.8, math.pi / 2, 1.0)
        self.Q.y = y
        e1 = Vector((self.Q.x - self.tray_half - 0.02, y, hel[-1].z))
        self.Q.z = e1.z
        straight2 = [hel[-1].lerp(e1, k / 30) for k in range(1, 31)]
        axis = smooth_polyline(straight1 + hel + straight2, 15)
        self.chute1_axis = axis
        self.collide(make_chute("Chute1", axis, rc=self.tray_rc))
        hx, hy = self.helix_c
        self.collide(cylinder("HelixPost", 0.06, top.z + 0.05, clay("lilac"), location=(hx, hy, (top.z + 0.05) / 2)))
        cylinder("HelixFoot", 0.16, 0.05, clay("lilac"), location=(hx, hy, 0.025))
        for u in (0.15, 0.5, 0.85):
            # spokes from the post out to the helix belly, just under the trough
            pt = hel[int(u * (len(hel) - 1))]
            ang = math.atan2(pt.y - hy, pt.x - hx)
            zz = pt.z - self.tray_rc - 0.035 - 0.03
            mid = Vector((hx + 0.21 * math.cos(ang), hy + 0.21 * math.sin(ang), zz))
            sp = cylinder("HelixSpoke", 0.02, 0.36, clay("lilac"), location=mid, axis="X")
            sp.rotation_euler = (0, 0, ang)
            self.collide(sp)

    def build_qualifier(self):
        Q = self.Q
        self.collide(cylinder("SorterBase", 0.36, 0.12, clay("lilac"), location=(Q.x, Q.y, 0.06), bevel=0.04))
        self.collide(cylinder("SorterColumn", 0.09, Q.z - 0.42, clay("lilac"), location=(Q.x, Q.y, 0.12 + (Q.z - 0.42 - 0.12) / 2 + 0.06)))
        # turntable head that yaws
        head = bpy.data.objects.new("SorterYaw", None)
        link(head)
        head.location = (Q.x, Q.y, Q.z)
        self.sorter_yaw = head
        collar = cylinder("SorterCollar", 0.14, 0.08, clay("gold"), location=(0, 0, -0.33), bevel=0.02)
        collar.parent = head
        for side in (-1, 1):
            arm = rounded_box("SorterFork", (0.05, 0.04, 0.34), clay("gold"), bevel=0.015,
                              location=(0, side * (self.tray_rc + 0.035 + 0.05), -0.15), subdiv=0)
            arm.parent = head
            self.collide(arm, animated=True)
        self.collide(collar, animated=True)
        tilt = bpy.data.objects.new("SorterTilt", None)
        link(tilt)
        tilt.parent = head
        self.sorter_tilt = tilt
        axis = [Vector((-self.tray_half + 0.8 * k / 40, 0, 0)) for k in range(41)]
        tray = make_chute("SorterTray", axis, rc=self.tray_rc, mat=clay("gold"))
        tray.parent = tilt
        self.collide(tray, animated=True)
        for side in (-1, 1):
            pin = cylinder("SorterPin", 0.03, 0.06, clay("ink"), location=(0, side * (self.tray_rc + 0.07), 0), axis="Y")
            pin.parent = tilt
        # a little gauge on the column: the needle swings to the verdict
        gauge = cylinder("Gauge", 0.11, 0.03, clay("cream"), location=(Q.x - 0.0, Q.y - 0.105, 1.15), axis="Y")
        self.collide(gauge)
        for k, col in enumerate(("lilac", "gold")):
            dot = cylinder("GaugeMark", 0.016, 0.01, clay(col), location=(Q.x + (-0.055 if k == 0 else 0.055), Q.y - 0.125, 1.19), axis="Y")
        needle_h = bpy.data.objects.new("GaugeNeedle", None)
        link(needle_h)
        needle_h.location = (Q.x, Q.y - 0.13, 1.15)
        needle = rounded_box("Needle", (0.012, 0.012, 0.085), clay("cardinal"), bevel=0.005, location=(0, 0, 0.04), subdiv=0)
        needle.parent = needle_h
        self.needle = needle_h

    def tray_matrix(self, yaw, tilt):
        return (Matrix.Translation(self.Q) @ Matrix.Rotation(yaw, 4, "Z") @ Matrix.Rotation(tilt, 4, "Y"))

    def build_desk_and_cart(self):
        zd = self.zd
        self.collide(rounded_box("DeskTop", (2.75, 1.35, 0.08), clay("creamdeep"), bevel=0.035,
                                 location=(-0.1, 0.3, zd - 0.04), wobble=0.003))
        for sx in (-1.33, 1.13):
            for sy in (-0.28, 0.88):
                self.collide(rounded_box("DeskLeg", (0.07, 0.07, zd - 0.08), clay("ink", rough=0.7), bevel=0.02,
                                         location=(sx, sy, (zd - 0.08) / 2), subdiv=0))
        # rails the cart rides on
        for ry in (-0.13, 0.13):
            rounded_box("CartRail", (2.3, 0.025, 0.012), clay("ink", rough=0.6), bevel=0.005,
                        location=(-0.2, ry, zd + 0.006), subdiv=0)
        cart = bpy.data.objects.new("Cart", None)
        link(cart)
        self.cart = cart
        chassis = rounded_box("CartChassis", (0.5, 0.34, 0.09), clay("gold"), bevel=0.03,
                              location=(0, 0, 0.125), subdiv=1)
        chassis.parent = cart
        self.collide(chassis, animated=True)
        self.wheels = []
        for wx in (-0.17, 0.17):
            for wy in (-0.17, 0.17):
                w = cylinder("CartWheel", 0.065, 0.04, clay("ink", rough=0.6), location=(wx, wy, 0.07), axis="Y", bevel=0.012)
                w.parent = cart
                hub = cylinder("CartHub", 0.022, 0.046, clay("cream"), location=(0, 0, 0), axis="Y", bevel=0.006)
                hub.parent = w
                self.wheels.append(w)
        hinge = bpy.data.objects.new("CartBedHinge", None)
        link(hinge)
        hinge.parent = cart
        hinge.location = (0.25, 0, 0.17)
        self.bed_hinge = hinge
        bed = rounded_box("CartBed", (0.5, 0.34, 0.04), clay("cream"), bevel=0.015, location=(-0.25, 0, 0.02), subdiv=1)
        bed.parent = hinge
        stop = rounded_box("CartStop", (0.03, 0.34, 0.1), clay("cream"), bevel=0.012, location=(-0.485, 0, 0.09), subdiv=0)
        stop.parent = hinge
        for sy in (-0.16, 0.16):
            rail = rounded_box("CartSide", (0.48, 0.02, 0.05), clay("cream"), bevel=0.008, location=(-0.25, sy, 0.065), subdiv=0)
            rail.parent = hinge
            self.collide(rail, animated=True)
        self.collide(bed, animated=True)
        self.collide(stop, animated=True)
        # local frame of the hinge: bed top at z = +0.04, ball rests against the stop
        self.ball_on_bed = Vector((-0.47 + R + 0.002, 0, 0.04 + R))
        self.env_on_bed = Vector((-0.13, 0, 0.04))

    def cart_world(self, x, tilt):
        base = Matrix.Translation((x, 0, self.zd))
        hinge = base @ Matrix.Translation((0.25, 0, 0.17)) @ Matrix.Rotation(tilt, 4, "Y")
        return base, hinge

    def build_writer(self):
        objs = append_part("writer.blend")
        root = root_of(objs, "Grp_LetterWritingMachine")
        self.wk = 2.0
        riser_h = 0.13
        self.collide(rounded_box("WriterRiser", (0.86, 0.5, riser_h), clay("lilac"), bevel=0.03,
                                 location=(0, 0.55, self.zd + riser_h / 2), subdiv=1))
        place(root, (0, 0.55, self.zd + riser_h), self.wk)
        self.writer_root = root
        self.writer_z = self.zd + riser_h
        for o in objs:
            if o.type == "MESH":
                self.collide(o)
        self.printhead = by_name(objs, "PrintHead_Assembly")
        self.printhead_rest = self.printhead.location.copy()
        # a short cream chute from the output ledge down to the cart bed
        ledge_y = 0.55 - 0.146 * self.wk
        self.ledge = Vector((0, ledge_y + 0.07, self.writer_z + 0.067 * self.wk))
        self.collide(rounded_box("OutputLip", (0.42, 0.12, 0.02), clay("cream"), bevel=0.008,
                                 location=(0, ledge_y - 0.04, self.ledge.z - 0.03), subdiv=0))

    def build_mailbox(self):
        objs = append_part("mailbox.blend")
        root = root_of(objs, "Cute toy mailbox assembly")
        k = 2.25
        self.mk = k
        floor_local = 0.289
        self.z_floor = self.zd + 0.15
        zm = self.z_floor - floor_local * k
        holder = place(root, (self.mail_x, 0, zm), k, rot_z=-math.pi / 2)
        self.collide(cylinder("MailPlinth", 0.3, zm, clay("cream"), location=(self.mail_x, 0.04, zm / 2), bevel=0.04))
        self.door = by_name(objs, "Door")
        self.flag = by_name(objs, "Flag")
        body = by_name(objs, "Body")
        self.mail_objs = objs
        # back exit: a round hole through the rear wall
        hole_z = self.z_floor + R + 0.01
        back_x = self.mail_x + 0.15 * k
        cutter = cylinder("MailHoleCutter", 0.135, 0.3, None, location=(back_x, 0, hole_z), axis="X", bevel=0)
        cutter.hide_render = cutter.hide_viewport = True
        bmod = body.modifiers.new("backhole", "BOOLEAN")
        bmod.operation = "DIFFERENCE"
        bmod.object = cutter
        bmod.solver = "EXACT"
        self.mail_back_x = back_x
        self.mail_front_x = self.mail_x - 0.15 * k
        for o in objs:
            if o.type == "MESH":
                anim = o == self.door or o == self.flag or (o.parent in (self.door, self.flag))
                self.collide(o, animated=anim)
        self.door.rotation_mode = "XYZ"
        self.flag.rotation_mode = "XYZ"

    def build_reject(self):
        pass  # built after the qualifier exit pose is known (build_chute2)

    def build_chute2(self):
        rc = self.tray_rc
        # accepted exit
        M = self.tray_matrix(self.yaw_acc, self.tilt_max)
        e2 = M @ Vector((self.tray_half + 0.02, 0, 0))
        tdir = (M.to_3x3() @ Vector((1, 0, 0))).normalized()
        land = self.cart_world(self.xL, 0)[1] @ self.ball_on_bed
        end = Vector((land.x + 0.0, land.y + 0.16, land.z + 0.17 + rc - R))
        e2b = e2 + tdir * 0.25
        span = e2b.z - end.z
        pts = [e2, e2b, Vector((-1.5, 0.74, e2b.z - 0.3 * span)), Vector((-1.25, 0.93, e2b.z - 0.55 * span)),
               Vector((land.x, 0.74, e2b.z - 0.8 * span)), Vector((land.x, 0.45, end.z + 0.015)), end]
        axis = catmull(pts)
        self.chute2_axis = axis
        self.collide(make_chute("Chute2", axis, rc=rc))
        for frac in (0.35, 0.6):
            self.collide(strut_under("Chute2Strut", axis, frac, clay("cream"), floor=self.zd))
        # rejected exit
        M = self.tray_matrix(self.yaw_rej, self.tilt_max)
        e2 = M @ Vector((self.tray_half + 0.02, 0, 0))
        tdir = (M.to_3x3() @ Vector((1, 0, 0))).normalized()
        h = self.hole_c
        pts = [e2, e2 + tdir * 0.2, Vector((-1.45, -0.75, 1.55)), Vector((-1.35, -1.1, 1.05)),
               Vector((-1.45, -1.35, 0.62)), Vector((h.x + 0.02, h.y + 0.12, 0.42))]
        axis = catmull(pts)
        self.reject_axis = axis
        self.collide(make_chute("RejectChute", axis, rc=rc, mat=clay("lilac")))
        self.collide(strut_under("RejectStrut", axis, 0.3, clay("lilac")))

    def build_chute3_and_stack(self):
        rc = self.tray_rc
        z_ball = self.z_floor + R
        start = Vector((self.mail_back_x + 0.03, 0, z_ball + rc - R))
        s = self.stack_c
        pts = [start, start + Vector((0.3, 0, -0.03)), Vector((2.82, -0.02, start.z - 0.08)),
               Vector((3.0, -0.14, start.z - 0.13)), Vector((s.x, s.y + 0.32, start.z - 0.17))]
        axis = catmull(pts)
        self.chute3_axis = axis
        self.collide(make_chute("Chute3", axis, rc=rc))
        st = self.collide(strut_under("Chute3Strut", axis, 0.55, clay("cream")))
        self.collide(cylinder("Chute3Foot", 0.08, 0.03, clay("cream"), location=(st.location.x, st.location.y, 0.015)))
        self.collide(rounded_box("StackBase", (0.62, 0.62, 0.06), clay("sky"), bevel=0.025,
                                 location=(s.x, s.y, 0.03)))
        self.slab_h = 0.1
        self.slab_w = 0.46

    def build_props(self):
        objs = append_part("props.blend")
        zd = self.zd
        spots = {"Wrench": ((-1.0, -0.62, 0.0), 2.4, 0.5),
                 "StickyNote": ((-1.15, 0.72, zd), 3.0, -0.25),
                 "Pencil": ((0.85, 0.78, zd), 3.0, 1.2)}
        bpy.context.view_layer.update()
        for name, (loc, k, rz) in spots.items():
            root = next((o for o in objs if o.name == name), None)
            if root is None:
                continue
            mn, mx = world_bbox([root] + descendants(root))
            ctr = Vector(((mn.x + mx.x) / 2, (mn.y + mx.y) / 2, mn.z))
            holder = bpy.data.objects.new(name + "_place", None)
            link(holder, root.users_collection[0])
            holder.location = loc
            holder.rotation_euler = (0, 0, rz)
            holder.scale = (k,) * 3
            mw = root.matrix_world.copy()
            root.parent = holder
            root.matrix_parent_inverse = Matrix.Translation(-ctr)
            root.matrix_basis = mw
        for o in objs:
            if o.parent is None and o.type == "EMPTY" and not o.name.endswith("_place"):
                o.location = (-1.0, 0.75, zd)

    def build_light_world(self):
        light_rig()


# ---------------------------------------------------------------- choreography

class Show:
    """Every ball's position for every frame, plus every mechanism's pose."""

    def __init__(self, m: Machine):
        self.m = m
        self.ts = frame_times()
        self.plan_paths()
        self.plan_balls()

    def plan_paths(self):
        m = self.m
        c, z = m.city_c, m.zc
        y = c.y + m.street_y
        zb = z + R
        # street from slot 0 to the chute
        street = [Vector((c.x + m.slot_x[0] + d, y, zb)) for d in np.linspace(0, 0.2, 10)]
        ch1 = chute_track(m.chute1_axis, m.tray_rc).p
        self.t1 = Track(street + ch1)
        self.d1, self.v1, self.s1 = self.t1.roll(0.85)
        # sorter: ball rolls in from E1 and stops at the centre, then yaw, tilt, roll out
        self.q_in = 0.32
        self.q_yaw = (0.30, 0.52)
        self.q_tilt = (0.50, 0.64)
        self.q_roll0 = 0.58
        self.q_back = (1.12, 1.24)
        self.q_yawback = (1.15, 1.31)
        # roll-out along the tilted tray
        acc = G * math.sin(m.tilt_max)
        self.q_exit = self.q_roll0 + math.sqrt(2 * (m.tray_half) / acc)
        self.v_tray = acc * (self.q_exit - self.q_roll0)
        assert self.q_exit < self.q_back[0], "sorter starts levelling before the ball has left"
        self.t2 = chute_track(m.chute2_axis, m.tray_rc)
        self.d2, self.v2, self.s2 = self.t2.roll(self.v_tray)
        self.tr = chute_track(m.reject_axis, m.tray_rc)
        self.dr, self.vr, self.sr = self.tr.roll(self.v_tray, damping=0.2)
        # chute 2 end to the cart bed: a short hop
        self.hop2 = 0.22
        self.t3 = chute_track(m.chute3_axis, m.tray_rc)
        # arrival times relative to release
        self.A1 = self.d1
        self.Aexit = self.A1 + self.q_exit
        self.C = self.Aexit + self.d2 + self.hop2  # lands on the cart
        print(f"PLAN chute1 {self.d1:.2f}s  sorter exit {self.Aexit:.2f}s  chute2 {self.d2:.2f}s  cart land {self.C:.2f}s")

    # cart and mailbox, relative to the landing time on the cart
    CART = dict(to_writer=(0.15, 0.65), env_out=(0.05, 0.45), fold=(0.45, 0.68), seal=(0.68, 0.78),
                env_slide=(0.78, 1.05), to_dump=(1.5, 2.15), door_open=(1.85, 2.15),
                tip=(2.12, 2.32), untip=(2.95, 3.15), door_close=(3.3, 3.55), flag_up=(3.45, 3.7),
                back=(3.1, 3.7), flag_down=(5.3, 5.6), print=(-0.3, 0.6))

    def plan_balls(self):
        m = self.m
        rng = random.Random(7)
        palette = ["sky", "gold", "lilac", "cream", "sky", "lilac", "ink", "gold", "cream"]
        self.release0 = -0.12
        self.ball_ids = list(range(-9, 9))
        self.colors = {i: ("cardinal" if i == HERO else palette[(i * 5 + 3) % len(palette)]) for i in self.ball_ids}
        self.accepted = {i for i in self.ball_ids if i % ACCEPT_EVERY == 0}
        self.cart_jobs = sorted(self.release0 + i * P + self.C for i in self.accepted)
        # post-cart path, built once with the real door and floor in place
        self.plan_mail_path()
        rng.random()

    def plan_mail_path(self):
        m = self.m
        _, hinge = m.cart_world(m.xD, m.tilt_max if hasattr(m, "tilt_max") else 0)
        tilt = math.radians(32)
        self.bed_tilt = tilt
        _, hinge = m.cart_world(m.xD, tilt)
        edge = hinge @ Vector((0.0, 0, 0.04 + R))
        zf = m.z_floor + R
        door_tip_x = m.mail_front_x - 0.183 * m.mk
        pts = [edge, Vector((edge.x + 0.05, 0, edge.z - 0.012)), Vector((door_tip_x + 0.06, 0, zf + 0.03)),
               Vector((m.mail_front_x, 0, zf + 0.012)), Vector((m.mail_front_x + 0.15, 0, zf)),
               Vector((m.mail_back_x - 0.05, 0, zf)), Vector((m.mail_back_x + 0.03, 0, zf))]
        path = catmull(pts, per_unit=80)
        tail = self.t3.p
        self.tm = Track(path + tail)
        # ball rolls on the tilted bed first
        acc = G * math.sin(tilt)
        bed_len = abs(m.ball_on_bed.x)
        self.bed_roll = math.sqrt(2 * bed_len / acc)
        v_edge = acc * self.bed_roll
        self.dm, self.vm, self.sm = self.tm.roll(v_edge, damping=0.3)
        self.mail_len_in = Track(path).length
        print(f"PLAN bed roll {self.bed_roll:.2f}s  mailbox+chute3 {self.dm:.2f}s")

    # ---- mechanism poses
    def sorter_pose(self, t):
        """(yaw, tilt, verdict) for absolute time t."""
        k = math.floor((t - self.release0 - self.A1) / P)
        i = k
        c = t - (self.release0 + i * P + self.A1)
        target = self.m.yaw_acc if i in self.accepted or i % ACCEPT_EVERY == 0 else self.m.yaw_rej
        yaw = target * (ramp(c, *self.q_yaw) - ramp(c, *self.q_yawback))
        tilt = self.m.tilt_max * (ramp(c, *self.q_tilt) - ramp(c, *self.q_back))
        verdict = (1 if i % ACCEPT_EVERY == 0 else -1) * (ramp(c, 0.25, 0.45) - ramp(c, 1.15, 1.3))
        return yaw, tilt, verdict

    def cart_job(self, t):
        """The cart job active at t: (C, c) with c = t - C, chosen so c spans the whole cycle."""
        best = None
        for C in self.cart_jobs:
            # hand over to the next job only once this one has fully returned
            if t >= C - 0.3:
                best = C
        if best is None:
            best = self.cart_jobs[0]
        return best, t - best

    def cart_pose(self, t):
        m = self.m
        C, c = self.cart_job(t)
        K = self.CART
        x = m.xL
        x += (m.xW - m.xL) * ramp(c, *K["to_writer"])
        x += (m.xD - m.xW) * ramp(c, *K["to_dump"])
        x += (m.xL - m.xD) * ramp(c, *K["back"])
        tilt = self.bed_tilt * (ramp(c, *K["tip"]) - ramp(c, *K["untip"]))
        return x, tilt

    def door_angle(self, t):
        C, c = self.cart_job(t)
        K = self.CART
        return (math.pi / 2) * (ramp(c, *K["door_open"]) - ramp(c, *K["door_close"]))

    def flag_angle(self, t):
        up = 0.0
        for C in self.cart_jobs:
            c = t - C
            a = back_out((c - self.CART["flag_up"][0]) / (self.CART["flag_up"][1] - self.CART["flag_up"][0]), 2.4) if c > self.CART["flag_up"][0] else 0
            a -= ramp(c, *self.CART["flag_down"])
            up = max(up, min(a, 1.4))
        return -math.pi / 2 * (1 - up)

    def gate_angle(self, t):
        u = (t - self.release0) % P
        u = (t - self.release0 + 0.15) % P
        return math.radians(80) * (ramp(u, 0.0, 0.13) - ramp(u, 0.62, 0.78))

    # ---- ball state
    def ball_state(self, i, t):
        """World position and scale for ball i at time t, or None while it is out of play."""
        m = self.m
        rel = self.release0 + i * P
        tau = t - rel
        c, zc = m.city_c, m.zc
        y = c.y + m.street_y
        if tau < -5 * P:
            return None
        if tau < 0:
            # queue in the street: pop up from the manhole, then tick forward a slot per period
            k = int(math.floor(-tau / P))  # slot index currently heading to
            u = tau + (k + 1) * P
            if k >= 4:
                # wait until the ball ahead has rolled clear of the manhole
                s = 0.0 if u < 0.42 else back_out((u - 0.42) / 0.28, 1.8)
                return Vector((c.x + m.slot_x[4], y, zc + R * max(s, 1e-3))), max(s, 0.0)
            frm, to = m.slot_x[k + 1], m.slot_x[k]
            x = frm + (to - frm) * ramp(u, 0.0, 0.4)
            return Vector((c.x + x, y, zc + R)), 1.0
        if tau < self.A1:
            return self.t1.at(sample_lookup(self.s1, tau)), 1.0
        cq = tau - self.A1
        if cq < self.q_exit:
            k = round((rel + self.A1 - self.release0 - self.A1) / P)
            yaw, tilt, _ = self.sorter_pose(t)
            if cq < self.q_in:
                v = self.v1
                u0 = -m.tray_half - 0.02
                x = cq / self.q_in
                # cubic Hermite from (u0, v) to (0, 0)
                h00, h10, h01 = 2 * x ** 3 - 3 * x ** 2 + 1, x ** 3 - 2 * x ** 2 + x, -2 * x ** 3 + 3 * x ** 2
                u = h00 * u0 + h10 * v * self.q_in + h01 * 0.0
            elif cq < self.q_roll0:
                u = 0.0
            else:
                acc = G * math.sin(m.tilt_max)
                u = 0.5 * acc * (cq - self.q_roll0) ** 2
            return m.tray_matrix(yaw, tilt) @ Vector((u, 0, -(m.tray_rc - R))), 1.0
        ce = tau - self.Aexit
        if i % ACCEPT_EVERY != 0:
            if ce < self.dr:
                return self.tr.at(sample_lookup(self.sr, ce)), 1.0
            # off the end of the reject chute: fall into the hole
            cf = ce - self.dr
            p0 = self.tr.p[-1]
            h = m.hole_c
            fall_t = 0.42
            if cf < fall_t:
                u = cf / fall_t
                xy = p0.lerp(Vector((h.x, h.y, 0)), min(1.0, u * 1.6))
                zz = p0.z - 0.5 * G * 1.4 * cf * cf
                return Vector((xy.x, xy.y, zz)), 1.0
            return None
        if ce < self.d2:
            return self.t2.at(sample_lookup(self.s2, ce)), 1.0
        ch = ce - self.d2
        C = rel + self.C
        if ch < self.hop2:
            p0 = self.t2.p[-1]
            x, tilt = self.cart_pose(t)
            _, hinge = m.cart_world(x, tilt)
            p1 = hinge @ m.ball_on_bed
            u = ch / self.hop2
            p = p0.lerp(p1, smooth(u))
            p.z = p0.z + (p1.z - p0.z) * u * u
            return p, 1.0
        c = t - C
        roll0 = self.CART["tip"][0] + 0.12
        if c < roll0:
            x, tilt = self.cart_pose(t)
            _, hinge = m.cart_world(x, tilt)
            return hinge @ m.ball_on_bed, 1.0
        cb = c - roll0
        if cb < self.bed_roll:
            x, tilt = self.cart_pose(t)
            _, hinge = m.cart_world(x, tilt)
            acc = G * math.sin(self.bed_tilt)
            u = m.ball_on_bed.x + 0.5 * acc * cb * cb
            return hinge @ Vector((u, 0, m.ball_on_bed.z)), 1.0
        cm = cb - self.bed_roll
        if cm < self.dm:
            return self.tm.at(sample_lookup(self.sm, cm)), 1.0
        # fly from chute 3 onto the stack, bounce once, then become a block
        cf = cm - self.dm
        p0 = self.tm.p[-1]
        land_t = rel + self.C + roll0 + self.bed_roll + self.dm
        top = self.slab_top(i)
        land = Vector((m.stack_c.x, m.stack_c.y, top + R))
        fl = self.flight_time(p0, land)
        if cf < fl:
            u = cf / fl
            p = p0.lerp(land, u)
            p.z = p0.z + (land.z - p0.z) * u + 0.5 * G * cf * (fl - cf) * (1 - u * 0.0) * 0.0 + self.arc(p0, land, fl, cf)
            return p, 1.0
        cs = cf - fl
        g0 = self.grow_start(i)
        if t < g0:
            bounce = 0.05 * max(0.0, math.sin(math.pi * min(cs / 0.2, 1.0)))
            return land + Vector((0, 0, bounce)), 1.0
        gu = (t - g0) / 0.38
        if gu >= 1:
            return None
        grow = back_out(gu, 1.4)
        s = 1.0 - smooth(gu * 1.15)
        return Vector((land.x, land.y, top + m.slab_h * grow + R * max(s, 0))), max(s, 0.0)

    def arc(self, p0, p1, fl, cf):
        # ballistic arc on top of the straight-line interpolation
        lin = p0.z + (p1.z - p0.z) * (cf / fl)
        z = p0.z + ((p1.z - p0.z) + 0.5 * G * fl * fl) / fl * cf - 0.5 * G * cf * cf
        return z - lin

    def flight_time(self, p0, p1):
        # fall height plus a little hop; fixed small arc speed
        dz = p0.z - p1.z
        return math.sqrt(2 * max(dz, 0.02) / G) + 0.08

    def land_time(self, i):
        rel = self.release0 + i * P
        roll0 = self.CART["tip"][0] + 0.12
        return rel + self.C + roll0 + self.bed_roll + self.dm

    def grow_start(self, i):
        lt = self.land_time(i)
        p0 = self.tm.p[-1]
        top = self.slab_top(i)
        return lt + self.flight_time(p0, Vector((0, 0, top + R))) + 0.3

    def stage_times(self):
        """Scene-time windows for the page captions, all from the hero's own timeline."""
        rel = self.release0 + HERO * P
        C = rel + self.C
        K = self.CART
        grow_end = self.grow_start(HERO) + 0.45
        t_end = T0 + (FRAMES - 1) / FPS
        assert t_end - grow_end > 1.3, f"pull-back too short: {t_end - grow_end:.2f}s"
        return {
            "tray": (T0 + 0.45, rel + 0.2),
            "sort": (rel + 0.2, C - 0.1),
            "type": (C - 0.1, C + K["to_dump"][0]),
            "mail": (C + K["to_dump"][0], C + K["flag_up"][1] + 0.25),
            "stack": (C + K["flag_up"][1] + 0.25, grow_end),
            "out": (grow_end, t_end),
        }

    def stage_frames(self):
        return {k: [int(round((a - T0) * FPS)) + 1, int(round((b - T0) * FPS)) + 1]
                for k, (a, b) in self.stage_times().items()}

    def slab_top(self, i):
        """Top of the stack the moment accepted ball i lands: every earlier
        accepted ball has long since become its own slab."""
        rank = sorted(self.accepted).index(i)
        return 0.06 + (self.base_slabs + rank) * self.m.slab_h


# ---------------------------------------------------------------- bake everything

def build_and_bake():
    bpy.ops.wm.read_factory_settings(use_empty=True)
    random.seed(3)
    m = Machine()
    show = Show(m)
    ts = show.ts
    # stack: decide base so the stack shows 4 slabs at frame 1
    show.base_slabs = 2

    # balls
    mats = {}
    ball_objs = {}
    for i in show.ball_ids:
        ob = sphere(f"Ball_{i:+d}", R, clay(show.colors[i], rough=0.45))
        add_wobble(ob, 0.0015)
        ball_objs[i] = ob
    positions = {i: [] for i in show.ball_ids}
    for i, ob in ball_objs.items():
        rot = Quaternion()
        prev = None
        mats_i = []
        for t in ts:
            st = show.ball_state(i, t)
            if st is None:
                pos, s = Vector((0, 0, -5)), 0.0
            else:
                pos, s = st
            if prev is not None and st is not None:
                d = pos - prev
                d.z = 0 if abs(d.z) < 1e-6 else d.z
                if d.length > 1e-6:
                    axis = Vector((0, 0, 1)).cross(d)
                    if axis.length > 1e-6:
                        rot = Quaternion(axis.normalized(), d.length / R) @ rot
            prev = pos if st is not None else None
            positions[i].append(None if st is None else (pos.copy(), s))
            mats_i.append(Matrix.LocRotScale(pos, rot, Vector((max(s, 0.0),) * 3)))
        bake_matrices(ob, mats_i)
    show.positions = positions
    show.ball_objs = ball_objs

    # sorter
    yaws, tilts, needles = [], [], []
    for t in ts:
        yaw, tilt, verdict = show.sorter_pose(t)
        yaws.append(yaw)
        tilts.append(tilt)
        needles.append(verdict * 0.7)
    fcurve_bake(m.sorter_yaw, "rotation_euler", [[0] * len(ts), [0] * len(ts), yaws])
    fcurve_bake(m.sorter_tilt, "rotation_euler", [[0] * len(ts), tilts, [0] * len(ts)])
    fcurve_bake(m.needle, "rotation_euler", [[0] * len(ts), needles, [0] * len(ts)])
    # gate
    fcurve_bake(m.gate, "rotation_euler", [[0] * len(ts), [-show.gate_angle(t) for t in ts], [0] * len(ts)])
    # cart
    xs, bed = [], []
    for t in ts:
        x, tilt = show.cart_pose(t)
        xs.append(x)
        bed.append(tilt)
    fcurve_bake(m.cart, "location", [xs, [0] * len(ts), [m.zd] * len(ts)])
    fcurve_bake(m.bed_hinge, "rotation_euler", [[0] * len(ts), bed, [0] * len(ts)])
    for w in m.wheels:
        w.rotation_mode = "XYZ"
        fcurve_bake(w, "rotation_euler", [[0] * len(ts), [(x - m.xL) / 0.065 for x in xs], [0] * len(ts)])
    # mailbox door and flag (Nalana's door opens about its local X; 0 is closed)
    fcurve_bake(m.door, "rotation_euler", [[show.door_angle(t) for t in ts], [0] * len(ts), [0] * len(ts)])
    fcurve_bake(m.flag, "rotation_euler", [[show.flag_angle(t) for t in ts], [0] * len(ts), [0] * len(ts)])
    # print head shuttles while a letter is being written
    ph = m.printhead
    rest = m.printhead_rest
    hx = []
    for t in ts:
        C, c = show.cart_job(t)
        a, b = show.CART["print"]
        on = ramp(c, a, a + 0.15) - ramp(c, b - 0.15, b)
        hx.append(rest.x + on * 0.09 * math.sin(2 * math.pi * 2.2 * (c - a)))
    fcurve_bake(ph, "location", [hx, [rest.y] * len(ts), [rest.z] * len(ts)])

    build_envelopes(m, show)
    build_stack(m, show)
    return m, show


def build_envelopes(m, show):
    env_mat = clay("cream", rough=0.7)
    flap_mat = clay("creamdeep", rough=0.7)
    ts = show.ts
    K = show.CART
    for n, C in enumerate(show.cart_jobs):
        if C + 3.4 < 0 or C - 1 > ts[-1]:
            continue
        root = bpy.data.objects.new(f"Envelope_{n}", None)
        link(root)
        body = rounded_box(f"EnvBody_{n}", (0.22, 0.15, 0.014), env_mat, bevel=0.005, location=(0, 0, 0.007), subdiv=0)
        body.parent = root
        hinge = bpy.data.objects.new(f"EnvHinge_{n}", None)
        link(hinge)
        hinge.parent = root
        hinge.location = (0, 0.075, 0.014)
        bm = bmesh.new()
        vs = [bm.verts.new(v) for v in [(-0.108, 0, 0), (0.108, 0, 0), (0, -0.09, 0)]]
        bm.faces.new(vs)
        bmesh.ops.solidify(bm, geom=bm.faces[:], thickness=0.004)
        flap = new_mesh_obj(f"EnvFlap_{n}", bm, flap_mat)
        flap.parent = hinge
        seal = cylinder(f"EnvSeal_{n}", 0.022, 0.006, clay("cardinal" if n == show.cart_jobs.index(min(show.cart_jobs, key=lambda c: abs(c - (show.release0 + HERO * P + show.C)))) else "gold"),
                        location=(0, 0.015, 0.02), bevel=0.002)
        seal.parent = root
        mats, flaps, seals = [], [], []
        ledge = m.ledge
        roll0 = K["tip"][0] + 0.06
        for t in ts:
            c = t - C
            yaw = Matrix.Rotation(0, 4, "Z")
            if c < K["env_out"][0] or c > K["tip"][0] + 0.9:
                mats.append(Matrix.LocRotScale(Vector((0, 0.6, m.writer_z + 0.1)), None, Vector((0, 0, 0))))
            elif c < K["env_slide"][0]:
                u = ramp(c, *K["env_out"])
                p = Vector((0, ledge.y + 0.16 * (1 - u), ledge.z))
                mats.append(Matrix.Translation(p))
            elif c < K["env_slide"][1]:
                u = ramp(c, *K["env_slide"])
                x, tilt = show.cart_pose(t)
                _, h = m.cart_world(x, tilt)
                target = h @ Matrix.Translation(m.env_on_bed)
                p0 = Matrix.Translation(ledge)
                p = p0.to_translation().lerp(target.to_translation(), u)
                p.z += 0.04 * math.sin(math.pi * u)
                mats.append(Matrix.Translation(p))
            else:
                x, tilt = show.cart_pose(t)
                _, h = m.cart_world(x, tilt)
                if c < roll0:
                    mats.append(h @ Matrix.Translation(m.env_on_bed))
                else:
                    cb = c - roll0
                    acc = G * math.sin(show.bed_tilt) * 0.8
                    u = m.env_on_bed.x + 0.5 * acc * cb * cb
                    if u < 0.1:
                        mats.append(h @ Matrix.Translation((u, 0, m.env_on_bed.z)))
                    else:
                        # off the bed: slide across the door into the mailbox, then gone
                        edge = h @ Vector((0.1, 0, m.env_on_bed.z))
                        d = (u - 0.1)
                        p = Vector((edge.x + d, 0, max(m.z_floor + 0.002, edge.z - d * 0.5)))
                        if p.x > m.mail_front_x + 0.2:
                            mats.append(Matrix.LocRotScale(p, None, Vector((0, 0, 0))))
                        else:
                            mats.append(Matrix.Translation(p))
            flaps.append(math.radians(165) * (1 - ramp(c, *K["fold"])))
            seals.append(back_out((c - K["seal"][0]) / 0.12, 2.0) if c > K["seal"][0] else 0.0)
        bake_matrices(root, mats)
        fcurve_bake(hinge, "rotation_euler", [[-a for a in flaps], [0] * len(ts), [0] * len(ts)])
        fcurve_bake(seal, "scale", [seals, seals, seals])


def build_stack(m, show):
    ts = show.ts
    cols = ["cream", "gold"]
    s = m.stack_c
    rng = random.Random(11)
    n_static = show.base_slabs
    slabs = []
    for k in range(n_static):
        slabs.append((k, None))
    growers = sorted(show.accepted)  # one slab per accepted ball, in order
    for j in growers:
        slabs.append((None, j))
    level = 0
    show.slab_objs = []
    for idx, (k, j) in enumerate(slabs):
        col = cols[idx % 2]
        ob = rounded_box(f"Slab_{idx}", (m.slab_w, m.slab_w, m.slab_h - 0.006), clay(col), bevel=0.035,
                         location=(0, 0, 0), wobble=0.003)
        dotcol = show.colors[j] if j is not None else rng.choice(["sky", "lilac", "cardinal", "gold", "cream"])
        if dotcol == col:
            dotcol = "sky"
        dot = cylinder(f"SlabDot_{idx}", 0.045, 0.02, clay(dotcol), location=(0, -m.slab_w / 2 - 0.004, 0), axis="Y", bevel=0.006)
        dot.parent = ob
        jit = rng.uniform(-0.07, 0.07)
        z0 = 0.06 + idx * m.slab_h + (m.slab_h - 0.006) / 2
        mats = []
        for t in ts:
            if j is None:
                sc_ = 1.0
            else:
                g0 = show.grow_start(j)
                sc_ = back_out((t - g0) / 0.38, 1.4) if t > g0 else 0.0
            zz = 0.06 + idx * m.slab_h + (m.slab_h - 0.006) / 2 * max(sc_, 1e-3)
            mats.append(Matrix.LocRotScale(Vector((s.x, s.y, zz)), Quaternion((0, 0, 1), jit),
                                           Vector((1.0 if sc_ > 0 else 0, 1.0 if sc_ > 0 else 0, max(sc_, 0.0)))))
        bake_matrices(ob, mats)
        m.collide(ob, animated=True)
        show.slab_objs.append((ob, j))


# ---------------------------------------------------------------- collision audit

def audit(m, show, every=1):
    """Fail loudly if any ball ever overlaps geometry or another ball, or teleports."""
    sc = bpy.context.scene
    tol = 0.006
    statics, animated = [], []
    dg = bpy.context.evaluated_depsgraph_get()
    for ob, anim in m.colliders:
        if ob.type != "MESH":
            continue
        (animated if anim else statics).append(ob)
    def tree(ob):
        ev = ob.evaluated_get(dg)
        me = ev.to_mesh()
        bm = bmesh.new()
        bm.from_mesh(me)
        ev.to_mesh_clear()
        if not bm.faces:
            return None
        return BVHTree.FromBMesh(bm)
    sc.frame_set(1)
    dg = bpy.context.evaluated_depsgraph_get()
    static_trees = [(ob, tree(ob), ob.matrix_world.copy()) for ob in statics]
    static_trees = [s for s in static_trees if s[1] is not None]
    problems = []
    for f in range(1, FRAMES + 1, every):
        sc.frame_set(f)
        dg = bpy.context.evaluated_depsgraph_get()
        anim_trees = []
        for ob in animated:
            mw = ob.matrix_world.copy()
            if abs(mw.determinant()) < 1e-9:
                continue
            tr = tree(ob)
            if tr:
                anim_trees.append((ob, tr, mw))
        live = []
        for i in show.ball_ids:
            st = show.positions[i][f - 1]
            if st is None or st[1] < 0.98:
                continue
            p = st[0]
            if p.z < 0.0:
                continue
            live.append((i, p))
            for ob, tr, mw in static_trees + anim_trees:
                inv = mw.inverted()
                q = inv @ p
                hit = tr.find_nearest(q, R * 3)
                if hit[0] is None:
                    continue
                w = mw @ hit[0]
                d = (w - p).length
                if d < R - tol:
                    problems.append(f"frame {f}: ball {i:+d} at {tuple(round(v, 3) for v in p)} is {R - d:.3f} inside {ob.name}")
        for a in range(len(live)):
            for b in range(a + 1, len(live)):
                d = (live[a][1] - live[b][1]).length
                if d < 2 * R - tol:
                    problems.append(f"frame {f}: balls {live[a][0]:+d} and {live[b][0]:+d} overlap by {2 * R - d:.3f}")
    for i in show.ball_ids:
        seq = show.positions[i]
        for f in range(1, len(seq)):
            if seq[f] and seq[f - 1] and seq[f][1] > 0.98 and seq[f - 1][1] > 0.98:
                jump = (seq[f][0] - seq[f - 1][0]).length
                if jump > 0.25:
                    problems.append(f"frame {f + 1}: ball {i:+d} jumps {jump:.2f} in one frame")
    if problems:
        print("AUDIT FAILED", len(problems))
        seen = {}
        for p in problems:
            key = p.split(" is ")[-1].split(" inside ")[-1] if " inside " in p else p
            seen.setdefault(key, []).append(p)
        for key, ps in list(seen.items())[:40]:
            print("  ", ps[0], f"(+{len(ps) - 1} more like it)")
        raise SystemExit(2)
    print("AUDIT OK: no ball touches geometry, no overlaps, no jumps across", FRAMES, "frames")


# ---------------------------------------------------------------- camera

def build_camera(m, show, portrait=False):
    sc = bpy.context.scene
    cam = bpy.data.objects.new("Camera", bpy.data.cameras.new("Camera"))
    link(cam)
    sc.camera = cam
    cam.data.lens = 50
    cam.data.sensor_width = 36
    cam.data.dof.use_dof = True
    cam.data.dof.aperture_fstop = 5.6
    ts = show.ts
    hero = []
    last = None
    for f in range(len(ts)):
        st = show.positions[HERO][f]
        if st is not None and st[1] > 0.3:
            last = st[0].copy()
        hero.append(last.copy() if last else Vector((m.city_c.x + m.slot_x[0], m.city_c.y, m.zc)))
    # heavy smoothing: the camera drifts after the ball rather than snapping to it
    arr = np.array([[v.x, v.y, v.z] for v in hero])
    sig = 9.0
    k = np.arange(-30, 31)
    w = np.exp(-0.5 * (k / sig) ** 2)
    w /= w.sum()
    pad = np.pad(arr, ((30, 30), (0, 0)), mode="edge")
    sm = np.stack([np.convolve(pad[:, d], w, mode="valid") for d in range(3)], axis=1)
    wide_target = Vector((-0.95, -0.05, 1.0))
    st = show.stage_times()
    out0, t_end = st["out"]
    locs, rots, focus, lens, fstops = [], [], [], [], []
    for f, t in enumerate(ts):
        tgt = Vector(sm[min(f + 6, len(sm) - 1)])
        tgt.z -= 0.05
        # opening: very close and defocused, then rack and pull back onto the tray
        o = smoother((t - T0 - 0.2) / 1.1)
        reveal = smoother((t - out0) / (t_end - out0))
        az = math.radians(-26 + 18 * (t / 10.0)) * (1 - reveal) + math.radians(-14) * reveal
        el = math.radians(21 * (1 - reveal) + 34 * reveal)
        follow = (4.4 + 0.3 * math.sin(t * 0.6))
        dist = (1.1 * (1 - o) + follow * o) * (1 - reveal) + 24.0 * reveal
        lens.append(50 * (1 - reveal) + 40 * reveal)
        if portrait:
            dist *= 1.45 * (1 - reveal) + 1.05 * reveal
        target = tgt.lerp(wide_target, reveal)
        d = Vector((math.sin(az) * math.cos(el), -math.cos(az) * math.cos(el), math.sin(el)))
        pos = target + d * dist
        locs.append(pos)
        rots.append((target - pos).to_track_quat("-Z", "Y"))
        sharp = (target - pos).length
        focus.append(14.0 * (1 - o) + sharp * o)
        fstops.append(1.0 * (1 - o) + 5.6 * o)
    bake_matrices(cam, [Matrix.LocRotScale(p, q, Vector((1, 1, 1))) for p, q in zip(locs, rots)])
    fcurve_bake(cam.data, "dof.focus_distance", [focus])
    fcurve_bake(cam.data, "lens", [lens])
    fcurve_bake(cam.data, "dof.aperture_fstop", [fstops])
    return cam


# ---------------------------------------------------------------- render setup

_BOOKEND = {}


def grain_image(size=512, seed=5):
    """Gaussian grain tile written to disk and loaded back: a generated,
    packed float image reached the compositor as black on Blender 5.2."""
    import tempfile
    path = os.path.join(tempfile.gettempdir(), f"tts_grain_{size}_{seed}.png")
    if not os.path.exists(path):
        rng = np.random.default_rng(seed)
        g = rng.normal(0.5, 0.17, (size, size)).clip(0, 1).astype(np.float32)
        tmp = bpy.data.images.new("grain_src", size, size)
        tmp.pixels.foreach_set(np.stack([g, g, g, np.ones_like(g)], axis=-1).ravel())
        tmp.filepath_raw = path
        tmp.file_format = "PNG"
        tmp.save()
        bpy.data.images.remove(tmp)
    img = bpy.data.images.load(path, check_existing=True)
    img.colorspace_settings.name = "Non-Color"
    return img


def setup_render(res_x, res_y, samples, threshold=0.02, grain=True):
    sc = bpy.context.scene
    # Pixel sizes below were tuned at 1600 wide; scale them with the frame so
    # the 2560 cut has the same soft edges, not edges 1.6 times harder.
    k = max(res_x, res_y) / 1600
    # The scene does not change topology between frames: keep the BVH and
    # the textures across the sequence instead of rebuilding them per frame.
    sc.render.use_persistent_data = True
    sc.render.engine = "CYCLES"
    prefs = bpy.context.preferences.addons["cycles"].preferences
    prefs.compute_device_type = "METAL"
    prefs.get_devices()
    for d in prefs.devices:
        d.use = d.type == "METAL"
    sc.cycles.device = "GPU"
    sc.cycles.samples = samples
    sc.cycles.use_adaptive_sampling = True
    sc.cycles.adaptive_threshold = threshold
    sc.cycles.use_denoising = True
    # OIDN on the GPU: on the CPU it fought every other job on the machine.
    if hasattr(sc.cycles, "denoising_use_gpu"):
        sc.cycles.denoising_use_gpu = True
    sc.cycles.max_bounces = 8
    sc.cycles.diffuse_bounces = 4
    sc.cycles.glossy_bounces = 3
    sc.cycles.sample_clamp_indirect = 4.0
    sc.render.resolution_x = res_x
    sc.render.resolution_y = res_y
    sc.render.resolution_percentage = 100
    sc.render.fps = FPS
    sc.frame_start, sc.frame_end = 1, FRAMES
    sc.render.film_transparent = False
    try:
        sc.view_settings.view_transform = _VIEW["view"]
        if _VIEW["look"] != "None":
            sc.view_settings.look = _VIEW["look"]
    except TypeError:
        sc.view_settings.view_transform = "Filmic"
    sc.view_settings.exposure = _VIEW["exposure"]
    sc.render.image_settings.file_format = "PNG"
    sc.render.image_settings.color_mode = "RGB"
    # film grain in the compositor, shifted every frame so it reads as film, not dirt
    ng = bpy.data.node_groups.new("Grain", "CompositorNodeTree")
    sc.compositing_node_group = ng
    ng.interface.new_socket("Image", in_out="OUTPUT", socket_type="NodeSocketColor")
    rl = ng.nodes.new("CompositorNodeRLayers")
    out = ng.nodes.new("NodeGroupOutput")
    gi = ng.nodes.new("CompositorNodeImage")
    gi.image = grain_image()
    tr = ng.nodes.new("CompositorNodeTranslate")
    for key in ("wrap_axis",):
        if hasattr(tr, key):
            setattr(tr, key, "BOTH")
    try:
        tr.inputs["Extension X"].default_value = "Repeat"
        tr.inputs["Extension Y"].default_value = "Repeat"
    except (KeyError, TypeError):
        pass
    # grain scales with the pixel (a * (1 + f * (g - 0.5))), so saturated and
    # dark objects get the same relative grain as the ground. Additive grain
    # turned the gold cube to sandpaper in lookdev v11.
    lift = ng.nodes.new("ShaderNodeMix")
    lift.data_type = "RGBA"
    lift.blend_type = "ADD"
    lift.inputs["Factor"].default_value = 1.0
    lift.inputs[7].default_value = (0.5, 0.5, 0.5, 1.0)
    mix = ng.nodes.new("ShaderNodeMix")
    mix.data_type = "RGBA"
    mix.blend_type = "MULTIPLY"
    # f = 0.26 with nearest sampling: ground std close to Clay's measured 0.026
    # --no-grain leaves it to the page: per-pixel grain in every frame of a
    # 2560 sequence tripled its WebP size, and the page draws the same grain
    # live at the screen's own pixels.
    mix.inputs["Factor"].default_value = 0.26 if grain else 0.0
    ng.links.new(gi.outputs["Image"], tr.inputs["Image"])
    ng.links.new(tr.outputs["Image"], lift.inputs[6])
    # bookends: frame 1 is a flat field of the ground colour (#F4EFE6) that the
    # page crossfades into; the last frames brighten to it at the edges
    fade = ng.nodes.new("ShaderNodeMix")
    fade.data_type = "RGBA"
    fade.blend_type = "MIX"
    fade.inputs[7].default_value = hexcol("ground")
    ell2 = ng.nodes.new("CompositorNodeEllipseMask")
    for key, val in (("Size", (0.62, 0.62)),):
        if key in ell2.inputs:
            ell2.inputs[key].default_value = val
    blur2 = ng.nodes.new("CompositorNodeBlur")
    if "Size" in blur2.inputs:
        blur2.inputs["Size"].default_value = (260 * k, 260 * k)
    ng.links.new(ell2.outputs[0], blur2.inputs[0])
    inv = ng.nodes.new("ShaderNodeMath")
    inv.operation = "SUBTRACT"
    inv.inputs[0].default_value = 1.0
    ng.links.new(blur2.outputs[0], inv.inputs[1])
    edge = ng.nodes.new("ShaderNodeMath")
    edge.name = "EdgeFade"
    edge.operation = "MULTIPLY"
    ng.links.new(inv.outputs[0], edge.inputs[0])
    full = ng.nodes.new("ShaderNodeMath")
    full.name = "FullFade"
    full.operation = "MAXIMUM"
    ng.links.new(edge.outputs[0], full.inputs[0])
    ng.links.new(full.outputs[0], fade.inputs["Factor"])
    ng.links.new(rl.outputs["Image"], fade.inputs[6])
    ng.links.new(fade.outputs[2], mix.inputs[6])
    ts = frame_times()
    end_t = ts[-1]
    full_v = [1.0 - smoother((t - T0 - 0.15) / 0.6) for t in ts]
    edge_v = [smoother((t - (end_t - 1.0)) / 0.9) for t in ts]
    fcurve_bake(ng, 'nodes["FullFade"].inputs[1].default_value', [full_v])
    fcurve_bake(ng, 'nodes["EdgeFade"].inputs[1].default_value', [edge_v])
    _BOOKEND["vig"] = [0.86 + 0.14 * max(fv, ev) for fv, ev in zip(full_v, edge_v)]
    ng.links.new(lift.outputs[2], mix.inputs[7])
    # gentle vignette: a soft ellipse, edges down to about 86%
    try:
        ell = ng.nodes.new("CompositorNodeEllipseMask")
        for key, val in (("Size", (0.95, 0.95)), ("Width", 0.95), ("Height", 0.95)):
            if key in ell.inputs:
                ell.inputs[key].default_value = val
        blur = ng.nodes.new("CompositorNodeBlur")
        for key, val in (("Size", (300 * k, 300 * k)),):
            if key in blur.inputs:
                blur.inputs[key].default_value = val
        ng.links.new(ell.outputs[0], blur.inputs[0])
        mr = ng.nodes.new("ShaderNodeMapRange")
        mr.name = "Vignette"
        mr.inputs["To Min"].default_value = 0.86
        fcurve_bake(ng, 'nodes["Vignette"].inputs[3].default_value', [_BOOKEND["vig"]])
        mr.inputs["To Max"].default_value = 1.0
        ng.links.new(blur.outputs[0], mr.inputs["Value"])
        vig = ng.nodes.new("ShaderNodeMix")
        vig.data_type = "RGBA"
        vig.blend_type = "MULTIPLY"
        vig.inputs["Factor"].default_value = 1.0
        ng.links.new(mix.outputs[2], vig.inputs[6])
        ng.links.new(mr.outputs["Result"], vig.inputs[7])
        ng.links.new(vig.outputs[2], out.inputs[0])
    except Exception as exc:
        print("vignette skipped:", exc)
        ng.links.new(mix.outputs[2], out.inputs[0])
    rng = random.Random(1)
    # whole-pixel offsets and nearest sampling: a fractional shift blurred the
    # grain to 40% of its strength
    try:
        tr.inputs["Interpolation"].default_value = "Nearest"
    except (KeyError, TypeError):
        pass
    xs = [float(rng.randint(-256, 256)) for _ in range(FRAMES)]
    ys = [float(rng.randint(-256, 256)) for _ in range(FRAMES)]
    try:
        fcurve_bake(ng, 'nodes["%s"].inputs[1].default_value' % tr.name, [xs])
        fcurve_bake(ng, 'nodes["%s"].inputs[2].default_value' % tr.name, [ys])
    except Exception as exc:
        print("grain offset not animated:", exc)


def main():
    argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", default="check", choices=["check", "stills", "frames", "save"])
    ap.add_argument("--out", default="/tmp/machine")
    ap.add_argument("--frames", default="1-300")
    ap.add_argument("--portrait", action="store_true")
    ap.add_argument("--res", type=int, default=0, help="width override for previews")
    ap.add_argument("--samples", type=int, default=32)
    ap.add_argument("--threshold", type=float, default=0.03)
    ap.add_argument("--stills", default="1,40,75,110,140,170,200,225,250,300")
    ap.add_argument("--skip-audit", action="store_true")
    ap.add_argument("--no-grain", action="store_true")
    ap.add_argument("--stages", default="", help="write stage frame ranges as JSON here")
    ap.add_argument("--look", default="v1", choices=["v1", "v2"],
                    help="v1 reproduces the shipped /way film; v2 is the clay look")
    ap.add_argument("--region", default="", help="render border x0,y0,x1,y1 in 0..1, for crops")
    a = ap.parse_args(argv)
    LOOK["name"] = a.look
    m, show = build_and_bake()
    if not a.skip_audit:
        audit(m, show)
    if a.stages:
        import json
        with open(a.stages, "w") as fh:
            json.dump(show.stage_frames(), fh)
        print("STAGES", show.stage_frames())
    if a.mode == "check":
        return
    build_camera(m, show, portrait=a.portrait)
    w, h = (720, 1280) if a.portrait else (1600, 900)
    if a.res:
        h = int(round(h * a.res / w / 2) * 2)
        w = a.res
    setup_render(w, h, a.samples, a.threshold, grain=not a.no_grain)
    os.makedirs(a.out, exist_ok=True)
    sc = bpy.context.scene
    if a.mode == "save":
        bpy.ops.wm.save_as_mainfile(filepath=os.path.join(a.out, "machine.blend"))
        return
    if a.mode == "stills":
        frames = [int(x) for x in a.stills.split(",")]
    else:
        lo, hi = (int(x) for x in a.frames.split("-"))
        frames = list(range(lo, hi + 1))
    if a.region:
        x0, y0, x1, y1 = (float(v) for v in a.region.split(","))
        sc.render.use_border = True
        sc.render.use_crop_to_border = True
        sc.render.border_min_x, sc.render.border_min_y = x0, y0
        sc.render.border_max_x, sc.render.border_max_y = x1, y1
    for f in frames:
        sc.frame_set(f)
        sc.render.filepath = os.path.join(a.out, f"f{f:04d}.png")
        bpy.ops.render.render(write_still=True)


if __name__ == "__main__":
    main()
